version: "3"

services:
  frontend:
    container_name: loja_virtual_frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/frontend
    ports:
      - "3000:3000"
    restart: always
    command: npm run dev
  