# Generated by Django 4.1.7 on 2023-02-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marca", models.CharField(max_length=50)),
                ("nome", models.CharField(max_length=50)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "preco_promo",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("descricao", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
