# Generated by Django 4.2.5 on 2023-09-09 19:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camisetas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cor', models.CharField(choices=[('BRANCO', 'Branco'), ('PRETO', 'Preto'), ('VERMELHO', 'Vermelho'), ('AZUL', 'Azul'), ('VERDE', 'Verde'), ('AMARELO', 'Amarelo'), ('LARANJA', 'Laranja'), ('ROSA', 'Rosa'), ('ROXO', 'Roxo'), ('MARROM', 'Marrom'), ('CINZA', 'Cinza')], max_length=64)),
                ('tamanho', models.CharField(choices=[('PP', 'Pequeno'), ('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande'), ('GG', 'Extra Grande')], max_length=64)),
                ('marca', models.CharField(choices=[('Nike', 'Nike'), ('Adidas', 'Adidas'), ('Puma', 'Puma'), ('Reebok', 'Reebok'), ('Converse', 'Converse'), ('New Balance', 'New Balance'), ('Vans', 'Vans'), ('Under Armour', 'Under Armour'), ('Fila', 'Fila'), ('ASICS', 'ASICS')], max_length=64)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('preco_promo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estoque', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Camiseta',
                'verbose_name_plural': 'Camisetas',
            },
        ),
    ]
