# Generated by Django 4.2.5 on 2023-09-09 20:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blusas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cor', models.CharField(choices=[('Branco', 'Branco'), ('Preto', 'Preto'), ('Vermelho', 'Vermelho'), ('Azul', 'Azul'), ('Verde', 'Verde'), ('Amarelo', 'Amarelo'), ('Laranja', 'Laranja'), ('Rosa', 'Rosa'), ('Roxo', 'Roxo'), ('Marrom', 'Marrom'), ('Cinza', 'Cinza')], max_length=64)),
                ('tamanho', models.CharField(choices=[('PP', 'Pequeno'), ('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande'), ('GG', 'Extra Grande')], max_length=64)),
                ('marca', models.CharField(choices=[('Nike', 'Nike'), ('Adidas', 'Adidas'), ('Puma', 'Puma'), ('Reebok', 'Reebok'), ('Converse', 'Converse'), ('New Balance', 'New Balance'), ('Vans', 'Vans'), ('Under Armour', 'Under Armour'), ('Fila', 'Fila'), ('ASICS', 'ASICS')], max_length=64)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('preco_promo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estoque', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Blusa',
                'verbose_name_plural': 'Blusas',
            },
        ),
        migrations.CreateModel(
            name='Calcas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cor', models.CharField(choices=[('Branco', 'Branco'), ('Preto', 'Preto'), ('Vermelho', 'Vermelho'), ('Azul', 'Azul'), ('Verde', 'Verde'), ('Amarelo', 'Amarelo'), ('Laranja', 'Laranja'), ('Rosa', 'Rosa'), ('Roxo', 'Roxo'), ('Marrom', 'Marrom'), ('Cinza', 'Cinza')], max_length=64)),
                ('tamanho', models.CharField(choices=[('PP', 'Pequeno'), ('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande'), ('GG', 'Extra Grande')], max_length=64)),
                ('marca', models.CharField(choices=[('Nike', 'Nike'), ('Adidas', 'Adidas'), ('Puma', 'Puma'), ('Reebok', 'Reebok'), ('Converse', 'Converse'), ('New Balance', 'New Balance'), ('Vans', 'Vans'), ('Under Armour', 'Under Armour'), ('Fila', 'Fila'), ('ASICS', 'ASICS')], max_length=64)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('preco_promo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estoque', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Calça',
                'verbose_name_plural': 'Calças',
            },
        ),
        migrations.AlterField(
            model_name='camisetas',
            name='cor',
            field=models.CharField(choices=[('Branco', 'Branco'), ('Preto', 'Preto'), ('Vermelho', 'Vermelho'), ('Azul', 'Azul'), ('Verde', 'Verde'), ('Amarelo', 'Amarelo'), ('Laranja', 'Laranja'), ('Rosa', 'Rosa'), ('Roxo', 'Roxo'), ('Marrom', 'Marrom'), ('Cinza', 'Cinza')], max_length=64),
        ),
    ]
